/**
 * react-native-calendar-range-picker
 * https://huurray.github.io/
 *
 * Generated by huurray
 * https://huurray.github.io/
 *
 * @format
 */

import React from 'react';
import {SafeAreaView, StatusBar} from 'react-native';
import CalendarList from './calendar';

const App = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <CalendarList
          onChange={props => {
            console.log(props);
          }}
        />
      </SafeAreaView>
    </>
  );
};

export default App;
