/**
 * react-native-calendar-range-picker
 * https://huurray.github.io/
 *
 * Generated by huurray
 * https://huurray.github.io/
 *
 * @format
 */

import Calendar from './Calendar';

export default Calendar;
